import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";


const montserrat = Montserrat({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-neutral-200">
      <body className={montserrat.className}>
      <Header />
        {children}
        </body>
    </html>
  );
}
